version: '3.4'

services:
######################################################################### elastic search ##################################################################################
##http://localhost:9200/_cat/nodes?v=true&pretty
  elasticsearch:
    container_name: es01-test
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.2
    ports:
      - 9200:9200 
      - 9300:9300
    environment:
      - node.name=es01-test
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g      
      - xpack.security.enabled=false
      - xpack.security.authc.api_key.enabled=true
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - backend  
################################################################################# kibana ##################################################################################      
  kibana:
    container_name: kib01-test
    image: docker.elastic.co/kibana/kibana:8.5.2    
    ports:
      - 5601:5601
    networks:
      - backend
    depends_on:
      - elasticsearch    
######################################################################### logstash ##################################################################################
  logstash:
    container_name: ls01-test
    image: docker.elastic.co/logstash/logstash:8.5.2
    ports:
      - 5044:5044
      - 28080:28080
    volumes:
      - ./logstash/conf.d/:/usr/share/logstash/pipeline/:ro
    networks:
      - backend
    depends_on:
      - elasticsearch
    restart: on-failure
######################################################################### APM ##################################################################################
  apm-server:
    container_name: apm-server
    build:
      context: apm
      dockerfile: Dockerfile
    image: apm-server
    ports:
      - 8200:8200  
    environment:
      - strict.perms=false
      - output.elasticsearch.hosts=["es01-test:9200"]
    #volumes:
    #  - ./apm/apm-server.docker.yml:/usr/share/apm-server/apm-server.yml:ro"
    networks:
      - backend
    depends_on:
      - elasticsearch
    restart: on-failure
########################################################## networks #######################################################################################################
networks:
  backend:
    name: backend
    driver: bridge
volumes:
  es_data:
    driver: local