version: '3.4'

services:
######################################################################### elastic search ##################################################################################
##http://localhost:9200/_cat/nodes?v=true&pretty
  elasticsearch:
    container_name: es01-test
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    ports:
      - 9200:9200 
      - 9300:9300
    environment:
      - node.name=es01-test
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/es-data:/usr/share/elasticsearch/data
    networks:
      - backend  
########################################################## networks #######################################################################################################
networks:
  backend:
    name: backend
    driver: bridge