version: '3.4'

services:
################################################################################# kibana ##################################################################################      
  kibana:
    container_name: kib01-test
    image: docker.elastic.co/kibana/kibana:7.13.1    
    environment:
      ELASTICSEARCH_URL: http://es01-test:9200
      ELASTICSEARCH_HOSTS: http://es01-test:9200
    ports:      
      - 5601:5601
    networks:
      - backend
########################################################## networks #######################################################################################################
networks:
  backend:
    name: backend
    driver: bridge