apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: microservices-apigateway-sale-api
  name: microservices-apigateway-sale-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: microservices-apigateway-sale-api
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: microservices-apigateway-sale-api
    spec:
      containers:
      - image: acrmicroservicesapigateway.azurecr.io/microservicesapigatewaysaleapi
        imagePullPolicy: ""
        name: microservices-apigateway-sale-api
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
